language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - phpenv config-rm xdebug.ini
  - ./.travis.scripts/compile.sh

notifications:
  email:
    - oliviergarcia@php.net
    - patrickallaert@php.net

script:
  - MYPHP=`which php`
  - export PATH=`dirname $MYPHP`:$PATH
  - $MYPHP -c /tmp/temp-php-config.ini -v
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$MYPHP $MYPHP -c /tmp/temp-php-config.ini run-tests.php -q -x --show-diff
